### PR TITLE
changing docs and shell scripts to invoke python3

### PR DESCRIPTION
**Pull request by dennybaa**
@pferrel I suggest to stop using the outdated python, since neither PredictionIO nr UR require so.

### CODE REVIEW

**Comment by pferrel** [comment]
Agreed, the pre-requisited say Python 3 as the default, so used with `python...` and same for scala 2.11 called with `scala`. Some distros use `python3` to invoke. but the scripts require it to be used as `python`.

**Comment by dennybaa** [comment]
@pferrel Are you going to merge this? I just wanna say that none of the UR scripts will work for us or our users anymore if not merged.

> Some distros use python3 to invoke. but the scripts require it to be used as python.

scripts might require..., though they are broken to comply with the standard setup for mainline distros which we use, namely debian/centos/rhel and alpine (used on containers).

If you'd like to keep up with the old way - usage of the wrong interpreter (`python`) binary, then these distros setup **has to be mangled**. We used to do this before for debian, namely used `update-alternatives` to make `python` to point version 3 binary. Though we don't do it anymore. Personally, I don't like the idea to deviate from the "distro standard way".

All distros use `python3` as a standard binary to invoke version 3 apps, while only some use an override where python binary actually points to version 3 interpreter. We support:
- Debian based installations:
  `python3`, no `python` available (available only if 2.7 is installed)
- Alpine
  `python3`, no `python` available (available only if 2.7 is installed)
- CentOS/RHEL
  `python` by default points to version 2.7 and it is installed by default!
  We use SCL (software collections repository) to install `rh-python35`. It **has to be enabled** by sourcing from the profile like `. /opt/rh/rh-python35/enable`
  `python3` and `python` are both available and point to the 3rd version interpreter when sourced.

So the desire to invoke `python` deviates from the default setup of the mainline distros (distros which we use). This definitely introduces inconsistency, while on debian/alpine the absence of `python`  will just break scripts from execution, on centos/rhel it will run with the wrong version of interpreter which itself may confuse an end user even more with weird dependency problems.

**Comment by pferrel** [comment]
No, I didn't want to merge or we'll have to increase the version # 

When on ubuntu I make py3 the default so invoking python invokes python3, I do the same on macOS. We can't do this?

**Comment by dennybaa** [comment]
Merge this when you are ready meanwhile to before running the integration test:
```bash
cd ~/ur; sed -i 's/python \(.*.py\)/python3 \1/' examples/integration-test
```

**Comment by pferrel** [comment]
Ok, I see your point but this will trigger a lot of doc problems and is contrary to how Java and Scala do upgrades. Also contrary to how Centos would work once you do an upgrade. What a mess.

A side bet is that this is fucked and will revert to `python` invoking `python3` in the next version of debian et al.

**Comment by dennybaa** [comment]
> A side bet is that this is fucked and will revert to python invoking python3 in the next version of debian et al.
This is not so important for us, even if it does there's always a "version" symlink. like on the picture https://i.gyazo.com/47216eacb3cb8273e3b12e2d8cd11fdc.png

**Pull request merged**
